; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z ; ControlRandomWalk::Update
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z DD imagerel $LN17@Update
	DD	imagerel $LN17@Update+103
	DD	imagerel $unwind$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z DD imagerel $LN17@Update+103
	DD	imagerel $LN17@Update+205
	DD	imagerel $chain$1$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z DD imagerel $LN17@Update+205
	DD	imagerel $LN17@Update+222
	DD	imagerel $chain$2$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z DD 021H
	DD	imagerel $LN17@Update
	DD	imagerel $LN17@Update+103
	DD	imagerel $unwind$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z DD 041521H
	DD	036815H
	DD	0a3405H
	DD	imagerel $LN17@Update
	DD	imagerel $LN17@Update+103
	DD	imagerel $unwind$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Update@ControlRandomWalk@@QEAAXAEAVWorld@@AEAVEntity@@M@Z DD 061001H
	DD	027810H
	DD	0b640aH
	DD	07006720aH
END
