; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??$?KM$0A@@glm@@YA?AU?$vec@$01M$0A@@0@AEBU10@M@Z ; glm::operator/<float,0>
PUBLIC	?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z ; ControlPlacePheremone::Update
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z DD imagerel $LN159@Update
	DD	imagerel $LN159@Update+61
	DD	imagerel $unwind$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$8$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z DD imagerel $LN159@Update+61
	DD	imagerel $LN159@Update+676
	DD	imagerel $chain$8$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$9$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z DD imagerel $LN159@Update+676
	DD	imagerel $LN159@Update+705
	DD	imagerel $chain$9$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z
;	COMDAT xdata
xdata	SEGMENT
$chain$9$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z DD 021H
	DD	imagerel $LN159@Update
	DD	imagerel $LN159@Update+61
	DD	imagerel $unwind$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$8$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z DD 0125221H
	DD	01f852H
	DD	02e844H
	DD	03d835H
	DD	04c82fH
	DD	06a822H
	DD	079815H
	DD	088810H
	DD	0a680bH
	DD	0196404H
	DD	imagerel $LN159@Update
	DD	imagerel $LN159@Update+61
	DD	imagerel $unwind$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Update@ControlPlacePheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@MM@Z DD 092101H
	DD	05b821H
	DD	097819H
	DD	01a340fH
	DD	016010fH
	DD	07008H
END
