; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??$?0U_Exact_args_t@std@@$0A@@?$tuple@$$V@std@@QEAA@U_Exact_args_t@1@@Z ; std::tuple<>::tuple<><std::_Exact_args_t,0>
PUBLIC	??$?0AEAH@?$_Tuple_val@H@std@@QEAA@AEAH@Z	; std::_Tuple_val<int>::_Tuple_val<int><int &>
PUBLIC	??$?0U_Exact_args_t@std@@AEAH$$V$0A@@?$tuple@H@std@@QEAA@U_Exact_args_t@1@AEAH@Z ; std::tuple<int>::tuple<int><std::_Exact_args_t,int &,0>
PUBLIC	??$?RAEBHAEBH@?$less@X@std@@QEBA_NAEBH0@Z	; std::less<void>::operator()<int const &,int const &>
PUBLIC	??$forward@$$QEAH@std@@YA$$QEAHAEAH@Z		; std::forward<int &&>
PUBLIC	??$?0U_Exact_args_t@std@@AEAHAEAH$0A@@?$tuple@HH@std@@QEAA@U_Exact_args_t@1@AEAH1@Z ; std::tuple<int,int>::tuple<int,int><std::_Exact_args_t,int &,int &,0>
PUBLIC	??$forward@AEAH@std@@YAAEAHAEAH@Z		; std::forward<int &>
PUBLIC	??$clamp@HU?$less@X@std@@@std@@YAAEBHAEBH00U?$less@X@0@@Z ; std::clamp<int,std::less<void> >
PUBLIC	??$?_0N@?$vec@$01M$0A@@glm@@QEAAAEAU01@N@Z	; glm::vec<2,float,0>::operator/=<double>
PUBLIC	??$get@$00HH@std@@YA$$QEAH$$QEAV?$tuple@HH@0@@Z	; std::get<1,int,int>
PUBLIC	??$get@$0A@HH@std@@YA$$QEAH$$QEAV?$tuple@HH@0@@Z ; std::get<0,int,int>
PUBLIC	??$<move>@AEAV?$tuple@HH@std@@@@YA$$QEAV?$tuple@HH@std@@AEAV01@@Z ; <move><std::tuple<int,int> &>
PUBLIC	??$?0AEAHAEAH$0A@@?$tuple@HH@std@@QEAA@AEAH0@Z	; std::tuple<int,int>::tuple<int,int><int &,int &,0>
PUBLIC	??$clamp@H@std@@YAAEBHAEBH00@Z			; std::clamp<int>
PUBLIC	??A?$vector@U?$vec@$01M$0A@@glm@@V?$allocator@U?$vec@$01M$0A@@glm@@@std@@@std@@QEAAAEAU?$vec@$01M$0A@@glm@@_K@Z ; std::vector<glm::vec<2,float,0>,std::allocator<glm::vec<2,float,0> > >::operator[]
PUBLIC	??A?$vector@MV?$allocator@M@std@@@std@@QEAAAEAM_K@Z ; std::vector<float,std::allocator<float> >::operator[]
PUBLIC	??A?$array@UPheremoneCached@@$01@std@@QEAAAEAUPheremoneCached@@_K@Z ; std::array<PheremoneCached,2>::operator[]
PUBLIC	?Update@ControlFollowPheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@M@Z ; ControlFollowPheremone::Update
PUBLIC	?GetStrengthGrid@PheremoneGrid@@QEAAAEAMHH@Z	; PheremoneGrid::GetStrengthGrid
PUBLIC	?GetDirectionGrid@PheremoneGrid@@QEAAAEAU?$vec@$01M$0A@@glm@@HH@Z ; PheremoneGrid::GetDirectionGrid
PUBLIC	?GetGridPos@PheremoneGrid@@QEAA?AV?$tuple@HH@std@@MM@Z ; PheremoneGrid::GetGridPos
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Update@ControlFollowPheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@M@Z DD imagerel $LN165@Update
	DD	imagerel $LN165@Update+634
	DD	imagerel $unwind$?Update@ControlFollowPheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@M@Z
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Update@ControlFollowPheremone@@QEAAXAEAVWorld@@AEAVEntity@@AEAUPheremoneGrid@@M@Z DD 060f01H
	DD	04740fH
	DD	02640aH
	DD	013405H
END
