; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	?size@?$vector@U?$vec@$01M$0A@@glm@@V?$allocator@U?$vec@$01M$0A@@glm@@@std@@@std@@QEBA_KXZ ; std::vector<glm::vec<2,float,0>,std::allocator<glm::vec<2,float,0> > >::size
PUBLIC	?GetStrengthFast@PheremoneGrid@@QEAAAEAMHH@Z	; PheremoneGrid::GetStrengthFast
PUBLIC	?GetDirectionFast@PheremoneGrid@@QEAAAEAU?$vec@$01M$0A@@glm@@HH@Z ; PheremoneGrid::GetDirectionFast
PUBLIC	?Update@PheremoneGrid@@QEAAXM@Z			; PheremoneGrid::Update
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Update@PheremoneGrid@@QEAAXM@Z DD imagerel $LN177@Update
	DD	imagerel $LN177@Update+73
	DD	imagerel $unwind$?Update@PheremoneGrid@@QEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?Update@PheremoneGrid@@QEAAXM@Z DD imagerel $LN177@Update+73
	DD	imagerel $LN177@Update+88
	DD	imagerel $chain$1$?Update@PheremoneGrid@@QEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?Update@PheremoneGrid@@QEAAXM@Z DD imagerel $LN177@Update+88
	DD	imagerel $LN177@Update+704
	DD	imagerel $chain$2$?Update@PheremoneGrid@@QEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$?Update@PheremoneGrid@@QEAAXM@Z DD imagerel $LN177@Update+704
	DD	imagerel $LN177@Update+1445
	DD	imagerel $chain$3$?Update@PheremoneGrid@@QEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$?Update@PheremoneGrid@@QEAAXM@Z DD imagerel $LN177@Update+1445
	DD	imagerel $LN177@Update+1451
	DD	imagerel $chain$4$?Update@PheremoneGrid@@QEAAXM@Z
;	COMDAT xdata
xdata	SEGMENT
$chain$4$?Update@PheremoneGrid@@QEAAXM@Z DD 021H
	DD	imagerel $LN177@Update
	DD	imagerel $LN177@Update+73
	DD	imagerel $unwind$?Update@PheremoneGrid@@QEAAXM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$?Update@PheremoneGrid@@QEAAXM@Z DD 021H
	DD	imagerel $LN177@Update+73
	DD	imagerel $LN177@Update+88
	DD	imagerel $chain$1$?Update@PheremoneGrid@@QEAAXM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?Update@PheremoneGrid@@QEAAXM@Z DD 020521H
	DD	0b7405H
	DD	imagerel $LN177@Update+73
	DD	imagerel $LN177@Update+88
	DD	imagerel $chain$1$?Update@PheremoneGrid@@QEAAXM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?Update@PheremoneGrid@@QEAAXM@Z DD 040c21H
	DD	0a640cH
	DD	095405H
	DD	imagerel $LN177@Update
	DD	imagerel $LN177@Update+73
	DD	imagerel $unwind$?Update@PheremoneGrid@@QEAAXM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Update@PheremoneGrid@@QEAAXM@Z DD 020601H
	DD	030025206H
END
