; Listing generated by Microsoft (R) Optimizing Compiler Version 19.22.27905.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BP@LCBPOPOI@Spacial?5hash?5ran?5out?5of?5space?6@ ; `string'
PUBLIC	??_C@_06BDKAMNCK@?5died?6@			; `string'
PUBLIC	??_C@_07DBDIABGE@Colony?5@			; `string'
PUBLIC	??_C@_0BD@KJLPHLLL@Info?5about?5entity?3@	; `string'
PUBLIC	??_C@_02KEGNLNML@?0?5@				; `string'
PUBLIC	??_C@_09BKHOEFBM@Position?3@			; `string'
PUBLIC	??_C@_07KBHBKPBF@Health?3@			; `string'
PUBLIC	??_C@_07CDHKLEPN@Energy?3@			; `string'
PUBLIC	??_C@_04JBAKGBBD@Age?3@				; `string'
PUBLIC	??_C@_0L@CCILMKOL@Held?5food?3@			; `string'
PUBLIC	??_C@_0BA@BLMCHBJI@Time?5from?5home?3@		; `string'
PUBLIC	??_C@_0BA@IKADLCFE@Time?5from?5food?3@		; `string'
EXTRN	__imp__time64:PROC
;	COMDAT ??_C@_0BA@IKADLCFE@Time?5from?5food?3@
CONST	SEGMENT
??_C@_0BA@IKADLCFE@Time?5from?5food?3@ DB 'Time from food:', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@BLMCHBJI@Time?5from?5home?3@
CONST	SEGMENT
??_C@_0BA@BLMCHBJI@Time?5from?5home?3@ DB 'Time from home:', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0L@CCILMKOL@Held?5food?3@
CONST	SEGMENT
??_C@_0L@CCILMKOL@Held?5food?3@ DB 'Held food:', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_04JBAKGBBD@Age?3@
CONST	SEGMENT
??_C@_04JBAKGBBD@Age?3@ DB 'Age:', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_07CDHKLEPN@Energy?3@
CONST	SEGMENT
??_C@_07CDHKLEPN@Energy?3@ DB 'Energy:', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_07KBHBKPBF@Health?3@
CONST	SEGMENT
??_C@_07KBHBKPBF@Health?3@ DB 'Health:', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_09BKHOEFBM@Position?3@
CONST	SEGMENT
??_C@_09BKHOEFBM@Position?3@ DB 'Position:', 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_02KEGNLNML@?0?5@
CONST	SEGMENT
??_C@_02KEGNLNML@?0?5@ DB ', ', 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0BD@KJLPHLLL@Info?5about?5entity?3@
CONST	SEGMENT
??_C@_0BD@KJLPHLLL@Info?5about?5entity?3@ DB 'Info about entity:', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_07DBDIABGE@Colony?5@
CONST	SEGMENT
??_C@_07DBDIABGE@Colony?5@ DB 'Colony ', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_06BDKAMNCK@?5died?6@
CONST	SEGMENT
??_C@_06BDKAMNCK@?5died?6@ DB ' died', 0aH, 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BP@LCBPOPOI@Spacial?5hash?5ran?5out?5of?5space?6@
CONST	SEGMENT
??_C@_0BP@LCBPOPOI@Spacial?5hash?5ran?5out?5of?5space?6@ DB 'Spacial hash'
	DB	' ran out of space', 0aH, 00H		; `string'
PUBLIC	??$?0$$V@?$_Compressed_pair@V?$allocator@M@std@@V?$_Vector_val@U?$_Simple_types@M@std@@@2@$00@std@@QEAA@U_Zero_then_variadic_args_t@1@@Z ; std::_Compressed_pair<std::allocator<float>,std::_Vector_val<std::_Simple_types<float> >,1>::_Compressed_pair<std::allocator<float>,std::_Vector_val<std::_Simple_types<float> >,1><>
PUBLIC	??0?$vector@MV?$allocator@M@std@@@std@@QEAA@XZ	; std::vector<float,std::allocator<float> >::vector<float,std::allocator<float> >
PUBLIC	??0Chunk@@QEAA@XZ				; Chunk::Chunk
PUBLIC	??$construct@VChunk@@$$V@?$_Default_allocator_traits@V?$allocator@VChunk@@@std@@@std@@SAXAEAV?$allocator@VChunk@@@1@QEAVChunk@@@Z ; std::_Default_allocator_traits<std::allocator<Chunk> >::construct<Chunk>
PUBLIC	??$_Unfancy@VChunk@@@std@@YAPEAVChunk@@PEAV1@@Z	; std::_Unfancy<Chunk>
PUBLIC	??$construct@V?$vector@MV?$allocator@M@std@@@std@@$$V@?$_Default_allocator_traits@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@SAXAEAV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@1@QEAV?$vector@MV?$allocator@M@std@@@1@@Z ; std::_Default_allocator_traits<std::allocator<std::vector<float,std::allocator<float> > > >::construct<std::vector<float,std::allocator<float> > >
PUBLIC	??$_Emplace_back@$$V@?$_Uninitialized_backout_al@V?$allocator@VChunk@@@std@@@std@@QEAAXXZ ; std::_Uninitialized_backout_al<std::allocator<Chunk> >::_Emplace_back<>
PUBLIC	??$_Copy_memmove@PEAMPEAM@std@@YAPEAMPEAM00@Z	; std::_Copy_memmove<float *,float *>
PUBLIC	??$_Get_unwrapped@M@std@@YAPEAMQEAM@Z		; std::_Get_unwrapped<float>
PUBLIC	??$_Emplace_back@$$V@?$_Uninitialized_backout_al@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@QEAAXXZ ; std::_Uninitialized_backout_al<std::allocator<std::vector<float,std::allocator<float> > > >::_Emplace_back<>
PUBLIC	??0?$_Uninitialized_backout_al@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@QEAA@PEAV?$vector@MV?$allocator@M@std@@@1@AEAV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@1@@Z ; std::_Uninitialized_backout_al<std::allocator<std::vector<float,std::allocator<float> > > >::_Uninitialized_backout_al<std::allocator<std::vector<float,std::allocator<float> > > >
PUBLIC	??1?$_Uninitialized_backout_al@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@QEAA@XZ ; std::_Uninitialized_backout_al<std::allocator<std::vector<float,std::allocator<float> > > >::~_Uninitialized_backout_al<std::allocator<std::vector<float,std::allocator<float> > > >
PUBLIC	?_Release@?$_Uninitialized_backout_al@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@QEAAPEAV?$vector@MV?$allocator@M@std@@@2@XZ ; std::_Uninitialized_backout_al<std::allocator<std::vector<float,std::allocator<float> > > >::_Release
PUBLIC	??0?$_Uninitialized_backout_al@V?$allocator@VChunk@@@std@@@std@@QEAA@PEAVChunk@@AEAV?$allocator@VChunk@@@1@@Z ; std::_Uninitialized_backout_al<std::allocator<Chunk> >::_Uninitialized_backout_al<std::allocator<Chunk> >
PUBLIC	??1?$_Uninitialized_backout_al@V?$allocator@VChunk@@@std@@@std@@QEAA@XZ ; std::_Uninitialized_backout_al<std::allocator<Chunk> >::~_Uninitialized_backout_al<std::allocator<Chunk> >
PUBLIC	?_Release@?$_Uninitialized_backout_al@V?$allocator@VChunk@@@std@@@std@@QEAAPEAVChunk@@XZ ; std::_Uninitialized_backout_al<std::allocator<Chunk> >::_Release
PUBLIC	?__autoclassinit2@?$_Uninitialized_backout_al@V?$allocator@VChunk@@@std@@@std@@QEAAX_K@Z ; std::_Uninitialized_backout_al<std::allocator<Chunk> >::__autoclassinit2
PUBLIC	?__autoclassinit2@?$_Uninitialized_backout_al@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@QEAAX_K@Z ; std::_Uninitialized_backout_al<std::allocator<std::vector<float,std::allocator<float> > > >::__autoclassinit2
PUBLIC	??$_Get_size_of_n@$0EOCE@@std@@YA_K_K@Z		; std::_Get_size_of_n<20004>
PUBLIC	??$_Get_size_of_n@$0BI@@std@@YA_K_K@Z		; std::_Get_size_of_n<24>
PUBLIC	??$_Uninitialized_value_construct_n@V?$allocator@VChunk@@@std@@@std@@YAPEAVChunk@@PEAV1@_KAEAV?$allocator@VChunk@@@0@@Z ; std::_Uninitialized_value_construct_n<std::allocator<Chunk> >
PUBLIC	??$_Uninitialized_move@PEAMV?$allocator@M@std@@@std@@YAPEAMQEAM0PEAMAEAV?$allocator@M@0@@Z ; std::_Uninitialized_move<float *,std::allocator<float> >
PUBLIC	??$_Uninitialized_value_construct_n@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@YAPEAV?$vector@MV?$allocator@M@std@@@0@PEAV10@_KAEAV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@0@@Z ; std::_Uninitialized_value_construct_n<std::allocator<std::vector<float,std::allocator<float> > > >
PUBLIC	??$forward@AEBV?$allocator@VChunk@@@std@@@std@@YAAEBV?$allocator@VChunk@@@0@AEBV10@@Z ; std::forward<std::allocator<Chunk> const &>
PUBLIC	??$forward@AEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@YAAEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@0@AEBV10@@Z ; std::forward<std::allocator<std::vector<float,std::allocator<float> > > const &>
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@VChunk@@@std@@V?$_Vector_val@U?$_Simple_types@VChunk@@@std@@@2@$00@std@@QEBAAEBV?$allocator@VChunk@@@2@XZ ; std::_Compressed_pair<std::allocator<Chunk>,std::_Vector_val<std::_Simple_types<Chunk> >,1>::_Get_first
PUBLIC	?_Get_first@?$_Compressed_pair@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@V?$_Vector_val@U?$_Simple_types@V?$vector@MV?$allocator@M@std@@@std@@@std@@@2@$00@std@@QEBAAEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@XZ ; std::_Compressed_pair<std::allocator<std::vector<float,std::allocator<float> > >,std::_Vector_val<std::_Simple_types<std::vector<float,std::allocator<float> > > >,1>::_Get_first
PUBLIC	?allocate@?$allocator@VChunk@@@std@@QEAAPEAVChunk@@_K@Z ; std::allocator<Chunk>::allocate
PUBLIC	?_Getal@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEBAAEBV?$allocator@VChunk@@@2@XZ ; std::vector<Chunk,std::allocator<Chunk> >::_Getal
PUBLIC	?max_size@?$_Default_allocator_traits@V?$allocator@VChunk@@@std@@@std@@SA_KAEBV?$allocator@VChunk@@@2@@Z ; std::_Default_allocator_traits<std::allocator<Chunk> >::max_size
PUBLIC	?allocate@?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@QEAAPEAV?$vector@MV?$allocator@M@std@@@2@_K@Z ; std::allocator<std::vector<float,std::allocator<float> > >::allocate
PUBLIC	?_Getal@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEBAAEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@XZ ; std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >::_Getal
PUBLIC	?max_size@?$_Default_allocator_traits@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@SA_KAEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@Z ; std::_Default_allocator_traits<std::allocator<std::vector<float,std::allocator<float> > > >::max_size
PUBLIC	?max_size@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@QEBA_KXZ ; std::vector<Chunk,std::allocator<Chunk> >::max_size
PUBLIC	?_Buy_raw@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_K@Z ; std::vector<Chunk,std::allocator<Chunk> >::_Buy_raw
PUBLIC	?_Xlength@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@CAXXZ ; std::vector<Chunk,std::allocator<Chunk> >::_Xlength
PUBLIC	?capacity@?$vector@MV?$allocator@M@std@@@std@@QEBA_KXZ ; std::vector<float,std::allocator<float> >::capacity
PUBLIC	?_Umove_if_noexcept1@?$vector@MV?$allocator@M@std@@@std@@AEAAXPEAM00U?$integral_constant@_N$00@2@@Z ; std::vector<float,std::allocator<float> >::_Umove_if_noexcept1
PUBLIC	?max_size@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@QEBA_KXZ ; std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >::max_size
PUBLIC	?_Buy_raw@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_K@Z ; std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >::_Buy_raw
PUBLIC	?_Xlength@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@CAXXZ ; std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >::_Xlength
PUBLIC	?_Ufill@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAPEAVChunk@@PEAV3@_KU_Value_init_tag@2@@Z ; std::vector<Chunk,std::allocator<Chunk> >::_Ufill
PUBLIC	?_Buy_nonzero@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_K@Z ; std::vector<Chunk,std::allocator<Chunk> >::_Buy_nonzero
PUBLIC	??1?$_Tidy_guard@V?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@@std@@QEAA@XZ ; std::_Tidy_guard<std::vector<Chunk,std::allocator<Chunk> > >::~_Tidy_guard<std::vector<Chunk,std::allocator<Chunk> > >
PUBLIC	??0?$_Vector_val@U?$_Simple_types@VChunk@@@std@@@std@@QEAA@XZ ; std::_Vector_val<std::_Simple_types<Chunk> >::_Vector_val<std::_Simple_types<Chunk> >
PUBLIC	?_Umove@?$vector@MV?$allocator@M@std@@@std@@AEAAPEAMPEAM00@Z ; std::vector<float,std::allocator<float> >::_Umove
PUBLIC	?_Umove_if_noexcept@?$vector@MV?$allocator@M@std@@@std@@AEAAXPEAM00@Z ; std::vector<float,std::allocator<float> >::_Umove_if_noexcept
PUBLIC	?_Calculate_growth@?$vector@MV?$allocator@M@std@@@std@@AEBA_K_K@Z ; std::vector<float,std::allocator<float> >::_Calculate_growth
PUBLIC	?_Change_array@?$vector@MV?$allocator@M@std@@@std@@AEAAXQEAM_K1@Z ; std::vector<float,std::allocator<float> >::_Change_array
PUBLIC	?_Ufill@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAPEAV?$vector@MV?$allocator@M@std@@@2@PEAV32@_KU_Value_init_tag@2@@Z ; std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >::_Ufill
PUBLIC	?_Buy_nonzero@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_K@Z ; std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >::_Buy_nonzero
PUBLIC	??1?$_Tidy_guard@V?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@@std@@QEAA@XZ ; std::_Tidy_guard<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > >::~_Tidy_guard<std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > > >
PUBLIC	??0?$_Vector_val@U?$_Simple_types@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@QEAA@XZ ; std::_Vector_val<std::_Simple_types<std::vector<float,std::allocator<float> > > >::_Vector_val<std::_Simple_types<std::vector<float,std::allocator<float> > > >
PUBLIC	??$_Construct_n_copies_of_ty@U_Value_init_tag@std@@@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z ; std::vector<Chunk,std::allocator<Chunk> >::_Construct_n_copies_of_ty<std::_Value_init_tag>
PUBLIC	??$?0AEBV?$allocator@VChunk@@@std@@$$V@?$_Compressed_pair@V?$allocator@VChunk@@@std@@V?$_Vector_val@U?$_Simple_types@VChunk@@@std@@@2@$00@std@@QEAA@U_One_then_variadic_args_t@1@AEBV?$allocator@VChunk@@@1@@Z ; std::_Compressed_pair<std::allocator<Chunk>,std::_Vector_val<std::_Simple_types<Chunk> >,1>::_Compressed_pair<std::allocator<Chunk>,std::_Vector_val<std::_Simple_types<Chunk> >,1><std::allocator<Chunk> const &>
PUBLIC	??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z ; std::vector<float,std::allocator<float> >::_Emplace_reallocate<float const &>
PUBLIC	??$construct@MAEBM@?$_Default_allocator_traits@V?$allocator@M@std@@@std@@SAXAEAV?$allocator@M@1@QEAMAEBM@Z ; std::_Default_allocator_traits<std::allocator<float> >::construct<float,float const &>
PUBLIC	??$forward@AEBM@std@@YAAEBMAEBM@Z		; std::forward<float const &>
PUBLIC	??$_Construct_n_copies_of_ty@U_Value_init_tag@std@@@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z ; std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >::_Construct_n_copies_of_ty<std::_Value_init_tag>
PUBLIC	??$?0AEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@$$V@?$_Compressed_pair@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@V?$_Vector_val@U?$_Simple_types@V?$vector@MV?$allocator@M@std@@@std@@@std@@@2@$00@std@@QEAA@U_One_then_variadic_args_t@1@AEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@1@@Z ; std::_Compressed_pair<std::allocator<std::vector<float,std::allocator<float> > >,std::_Vector_val<std::_Simple_types<std::vector<float,std::allocator<float> > > >,1>::_Compressed_pair<std::allocator<std::vector<float,std::allocator<float> > >,std::_Vector_val<std::_Simple_types<std::vector<float,std::allocator<float> > > >,1><std::allocator<std::vector<float,std::allocator<float> > > const &>
PUBLIC	??$min@H@std@@YAAEBHAEBH0@Z			; std::min<int>
PUBLIC	??A?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@QEAAAEAVChunk@@_K@Z ; std::vector<Chunk,std::allocator<Chunk> >::operator[]
PUBLIC	?_Orphan_range@?$vector@MV?$allocator@M@std@@@std@@AEBAXPEAM0@Z ; std::vector<float,std::allocator<float> >::_Orphan_range
PUBLIC	??A?$array@H$0BDII@@std@@QEAAAEAH_K@Z		; std::array<int,5000>::operator[]
PUBLIC	??0?$allocator@VChunk@@@std@@QEAA@XZ		; std::allocator<Chunk>::allocator<Chunk>
PUBLIC	??0?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@QEAA@_KAEBV?$allocator@VChunk@@@1@@Z ; std::vector<Chunk,std::allocator<Chunk> >::vector<Chunk,std::allocator<Chunk> >
PUBLIC	?_Unchecked_begin@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@QEAAPEAVChunk@@XZ ; std::vector<Chunk,std::allocator<Chunk> >::_Unchecked_begin
PUBLIC	?_Unchecked_end@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@QEAAPEAVChunk@@XZ ; std::vector<Chunk,std::allocator<Chunk> >::_Unchecked_end
PUBLIC	??$_Emplace_back_with_unused_capacity@AEBM@?$vector@MV?$allocator@M@std@@@std@@AEAAAEAMAEBM@Z ; std::vector<float,std::allocator<float> >::_Emplace_back_with_unused_capacity<float const &>
PUBLIC	??$emplace_back@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAAEAMAEBM@Z ; std::vector<float,std::allocator<float> >::emplace_back<float const &>
PUBLIC	?push_back@?$vector@MV?$allocator@M@std@@@std@@QEAAXAEBM@Z ; std::vector<float,std::allocator<float> >::push_back
PUBLIC	?AddParticle@?$SwapList@VEntity@@$0BIGKA@@@QEAA_NVEntity@@@Z ; SwapList<Entity,100000>::AddParticle
PUBLIC	?RemoveParticle@?$SwapList@VEntity@@$0BIGKA@@@QEAAXH@Z ; SwapList<Entity,100000>::RemoveParticle
PUBLIC	?GetChunk@?$ChunkArray@$0DOI@@@QEAAAEAVChunk@@MM@Z ; ChunkArray<1000>::GetChunk
PUBLIC	?GetChunkPos@?$ChunkArray@$0DOI@@@QEAA?AV?$tuple@HH@std@@MM@Z ; ChunkArray<1000>::GetChunkPos
PUBLIC	?GetChunkGrid@?$ChunkArray@$0DOI@@@QEAAAEAVChunk@@HH@Z ; ChunkArray<1000>::GetChunkGrid
PUBLIC	?_Unchecked_begin@?$array@VColonyController@@$04@std@@QEAAPEAVColonyController@@XZ ; std::array<ColonyController,5>::_Unchecked_begin
PUBLIC	?_Unchecked_end@?$array@VColonyController@@$04@std@@QEAAPEAVColonyController@@XZ ; std::array<ColonyController,5>::_Unchecked_end
PUBLIC	??0?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@QEAA@XZ ; std::allocator<std::vector<float,std::allocator<float> > >::allocator<std::vector<float,std::allocator<float> > >
PUBLIC	??0?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@QEAA@_KAEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@1@@Z ; std::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >::vector<std::vector<float,std::allocator<float> >,std::allocator<std::vector<float,std::allocator<float> > > >
PUBLIC	?UpdateEntities@World@@QEAAXXZ			; World::UpdateEntities
PUBLIC	?UpdateColonies@World@@QEAAXXZ			; World::UpdateColonies
PUBLIC	?UpdateCollisions@World@@QEAAXXZ		; World::UpdateCollisions
PUBLIC	?UpdateCollisionChunk@World@@QEAAXHHHH@Z	; World::UpdateCollisionChunk
PUBLIC	?UpdateCollisionSingleChunk@World@@QEAAXHH@Z	; World::UpdateCollisionSingleChunk
PUBLIC	?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z ; World::UpdateCollisionEntities
PUBLIC	?UpdateDeadEntities@World@@QEAAXXZ		; World::UpdateDeadEntities
PUBLIC	?UpdateSpacialHash@World@@QEAAXXZ		; World::UpdateSpacialHash
PUBLIC	??_H@YAXPEAX_K1P6APEAX0@Z@Z			; `vector constructor iterator'
PUBLIC	??0?$array@VColonyController@@$04@std@@QEAA@XZ	; std::array<ColonyController,5>::array<ColonyController,5>
PUBLIC	??0?$ChunkArray@$0DOI@@@QEAA@XZ			; ChunkArray<1000>::ChunkArray<1000>
PUBLIC	??0?$array@VEntity@@$09@std@@QEAA@XZ		; std::array<Entity,10>::array<Entity,10>
PUBLIC	??0?$SwapList@VEntity@@$09@@QEAA@XZ		; SwapList<Entity,10>::SwapList<Entity,10>
PUBLIC	??0?$array@VEntity@@$0BIGKA@@std@@QEAA@XZ	; std::array<Entity,100000>::array<Entity,100000>
PUBLIC	??0?$SwapList@VEntity@@$0BIGKA@@@QEAA@XZ	; SwapList<Entity,100000>::SwapList<Entity,100000>
PUBLIC	?PrintEntityInfo@World@@QEAAXMM@Z		; World::PrintEntityInfo
PUBLIC	?Update@World@@QEAAXM@Z				; World::Update
PUBLIC	??0World@@QEAA@XZ				; World::World
PUBLIC	?AddEntity@World@@QEAA_NVEntity@@@Z		; World::AddEntity
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$construct@VChunk@@$$V@?$_Default_allocator_traits@V?$allocator@VChunk@@@std@@@std@@SAXAEAV?$allocator@VChunk@@@1@QEAVChunk@@@Z DD imagerel $LN9@construct
	DD	imagerel $LN9@construct+38
	DD	imagerel $unwind$??$construct@VChunk@@$$V@?$_Default_allocator_traits@V?$allocator@VChunk@@@std@@@std@@SAXAEAV?$allocator@VChunk@@@1@QEAVChunk@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Emplace_back@$$V@?$_Uninitialized_backout_al@V?$allocator@VChunk@@@std@@@std@@QEAAXXZ DD imagerel $LN13@Emplace_ba
	DD	imagerel $LN13@Emplace_ba+59
	DD	imagerel $unwind$??$_Emplace_back@$$V@?$_Uninitialized_backout_al@V?$allocator@VChunk@@@std@@@std@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Copy_memmove@PEAMPEAM@std@@YAPEAMPEAM00@Z DD imagerel $LN4@Copy_memmo
	DD	imagerel $LN4@Copy_memmo+48
	DD	imagerel $unwind$??$_Copy_memmove@PEAMPEAM@std@@YAPEAMPEAM00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Uninitialized_value_construct_n@V?$allocator@VChunk@@@std@@@std@@YAPEAVChunk@@PEAV1@_KAEAV?$allocator@VChunk@@@0@@Z DD imagerel $LN56@Uninitiali
	DD	imagerel $LN56@Uninitiali+766
	DD	imagerel $unwind$??$_Uninitialized_value_construct_n@V?$allocator@VChunk@@@std@@@std@@YAPEAVChunk@@PEAV1@_KAEAV?$allocator@VChunk@@@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Uninitialized_move@PEAMV?$allocator@M@std@@@std@@YAPEAMQEAM0PEAMAEAV?$allocator@M@0@@Z DD imagerel $LN12@Uninitiali
	DD	imagerel $LN12@Uninitiali+52
	DD	imagerel $unwind$??$_Uninitialized_move@PEAMV?$allocator@M@std@@@std@@YAPEAMQEAM0PEAMAEAV?$allocator@M@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Uninitialized_value_construct_n@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@YAPEAV?$vector@MV?$allocator@M@std@@@0@PEAV10@_KAEAV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@0@@Z DD imagerel $LN42@Uninitiali
	DD	imagerel $LN42@Uninitiali+91
	DD	imagerel $unwind$??$_Uninitialized_value_construct_n@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@YAPEAV?$vector@MV?$allocator@M@std@@@0@PEAV10@_KAEAV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@0@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?allocate@?$allocator@VChunk@@@std@@QEAAPEAVChunk@@_K@Z DD imagerel $LN30@allocate
	DD	imagerel $LN30@allocate+46
	DD	imagerel $unwind$?allocate@?$allocator@VChunk@@@std@@QEAAPEAVChunk@@_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Buy_raw@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_K@Z DD imagerel $LN37@Buy_raw
	DD	imagerel $LN37@Buy_raw+69
	DD	imagerel $unwind$?_Buy_raw@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Xlength@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@CAXXZ DD imagerel $LN4@Xlength
	DD	imagerel $LN4@Xlength+18
	DD	imagerel $unwind$?_Xlength@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@CAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Buy_raw@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_K@Z DD imagerel $LN36@Buy_raw
	DD	imagerel $LN36@Buy_raw+40
	DD	imagerel $unwind$?_Buy_raw@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Xlength@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@CAXXZ DD imagerel $LN4@Xlength
	DD	imagerel $LN4@Xlength+18
	DD	imagerel $unwind$?_Xlength@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@CAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Buy_nonzero@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_K@Z DD imagerel $LN53@Buy_nonzer
	DD	imagerel $LN53@Buy_nonzer+69
	DD	imagerel $unwind$?_Buy_nonzero@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Umove@?$vector@MV?$allocator@M@std@@@std@@AEAAPEAMPEAM00@Z DD imagerel $LN19@Umove
	DD	imagerel $LN19@Umove+49
	DD	imagerel $unwind$?_Umove@?$vector@MV?$allocator@M@std@@@std@@AEAAPEAMPEAM00@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Change_array@?$vector@MV?$allocator@M@std@@@std@@AEAAXQEAM_K1@Z DD imagerel $LN39@Change_arr
	DD	imagerel $LN39@Change_arr+136
	DD	imagerel $unwind$?_Change_array@?$vector@MV?$allocator@M@std@@@std@@AEAAXQEAM_K1@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Ufill@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAPEAV?$vector@MV?$allocator@M@std@@@2@PEAV32@_KU_Value_init_tag@2@@Z DD imagerel $LN48@Ufill
	DD	imagerel $LN48@Ufill+91
	DD	imagerel $unwind$?_Ufill@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAPEAV?$vector@MV?$allocator@M@std@@@2@PEAV32@_KU_Value_init_tag@2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?_Buy_nonzero@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_K@Z DD imagerel $LN52@Buy_nonzer
	DD	imagerel $LN52@Buy_nonzer+40
	DD	imagerel $unwind$?_Buy_nonzero@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Construct_n_copies_of_ty@U_Value_init_tag@std@@@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z DD imagerel $LN71@Construct_
	DD	imagerel $LN71@Construct_+77
	DD	imagerel $unwind$??$_Construct_n_copies_of_ty@U_Value_init_tag@std@@@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z DD imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z DD imagerel $LN176@Emplace_re+70
	DD	imagerel $LN176@Emplace_re+387
	DD	imagerel $chain$2$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z DD imagerel $LN176@Emplace_re+387
	DD	imagerel $LN176@Emplace_re+394
	DD	imagerel $chain$4$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$5$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z DD imagerel $LN176@Emplace_re+394
	DD	imagerel $LN176@Emplace_re+400
	DD	imagerel $chain$5$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??$_Construct_n_copies_of_ty@U_Value_init_tag@std@@@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z DD imagerel $LN109@Construct_
	DD	imagerel $LN109@Construct_+132
	DD	imagerel $unwind$??$_Construct_n_copies_of_ty@U_Value_init_tag@std@@@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@QEAA@_KAEBV?$allocator@VChunk@@@1@@Z DD imagerel $LN80@vector
	DD	imagerel $LN80@vector+91
	DD	imagerel $unwind$??0?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@QEAA@_KAEBV?$allocator@VChunk@@@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?RemoveParticle@?$SwapList@VEntity@@$0BIGKA@@@QEAAXH@Z DD imagerel $LN13@RemovePart
	DD	imagerel $LN13@RemovePart+129
	DD	imagerel $unwind$?RemoveParticle@?$SwapList@VEntity@@$0BIGKA@@@QEAAXH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@QEAA@_KAEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@1@@Z DD imagerel $LN118@vector
	DD	imagerel $LN118@vector+154
	DD	imagerel $unwind$??0?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@QEAA@_KAEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@1@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateEntities@World@@QEAAXXZ DD imagerel $LN31@UpdateEnti
	DD	imagerel $LN31@UpdateEnti+217
	DD	imagerel $unwind$?UpdateEntities@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateColonies@World@@QEAAXXZ DD imagerel $LN116@UpdateColo
	DD	imagerel $LN116@UpdateColo+85
	DD	imagerel $unwind$?UpdateColonies@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$8$?UpdateColonies@World@@QEAAXXZ DD imagerel $LN116@UpdateColo+85
	DD	imagerel $LN116@UpdateColo+1494
	DD	imagerel $chain$8$?UpdateColonies@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$9$?UpdateColonies@World@@QEAAXXZ DD imagerel $LN116@UpdateColo+1494
	DD	imagerel $LN116@UpdateColo+1614
	DD	imagerel $chain$9$?UpdateColonies@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateCollisions@World@@QEAAXXZ DD imagerel $LN31@UpdateColl
	DD	imagerel $LN31@UpdateColl+217
	DD	imagerel $unwind$?UpdateCollisions@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateCollisionChunk@World@@QEAAXHHHH@Z DD imagerel $LN89@UpdateColl
	DD	imagerel $LN89@UpdateColl+155
	DD	imagerel $unwind$?UpdateCollisionChunk@World@@QEAAXHHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$6$?UpdateCollisionChunk@World@@QEAAXHHHH@Z DD imagerel $LN89@UpdateColl+155
	DD	imagerel $LN89@UpdateColl+421
	DD	imagerel $chain$6$?UpdateCollisionChunk@World@@QEAAXHHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$7$?UpdateCollisionChunk@World@@QEAAXHHHH@Z DD imagerel $LN89@UpdateColl+421
	DD	imagerel $LN89@UpdateColl+437
	DD	imagerel $chain$7$?UpdateCollisionChunk@World@@QEAAXHHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z DD imagerel $LN55@UpdateColl
	DD	imagerel $LN55@UpdateColl+82
	DD	imagerel $unwind$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$4$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z DD imagerel $LN55@UpdateColl+82
	DD	imagerel $LN55@UpdateColl+245
	DD	imagerel $chain$4$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$5$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z DD imagerel $LN55@UpdateColl+245
	DD	imagerel $LN55@UpdateColl+254
	DD	imagerel $chain$5$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD imagerel $LN57@UpdateColl
	DD	imagerel $LN57@UpdateColl+118
	DD	imagerel $unwind$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD imagerel $LN57@UpdateColl+118
	DD	imagerel $LN57@UpdateColl+132
	DD	imagerel $chain$0$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD imagerel $LN57@UpdateColl+132
	DD	imagerel $LN57@UpdateColl+251
	DD	imagerel $chain$1$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD imagerel $LN57@UpdateColl+251
	DD	imagerel $LN57@UpdateColl+591
	DD	imagerel $chain$2$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$3$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD imagerel $LN57@UpdateColl+591
	DD	imagerel $LN57@UpdateColl+614
	DD	imagerel $chain$3$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateDeadEntities@World@@QEAAXXZ DD imagerel $LN32@UpdateDead
	DD	imagerel $LN32@UpdateDead+26
	DD	imagerel $unwind$?UpdateDeadEntities@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?UpdateDeadEntities@World@@QEAAXXZ DD imagerel $LN32@UpdateDead+26
	DD	imagerel $LN32@UpdateDead+229
	DD	imagerel $chain$0$?UpdateDeadEntities@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?UpdateDeadEntities@World@@QEAAXXZ DD imagerel $LN32@UpdateDead+229
	DD	imagerel $LN32@UpdateDead+238
	DD	imagerel $chain$1$?UpdateDeadEntities@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?UpdateDeadEntities@World@@QEAAXXZ DD imagerel $LN32@UpdateDead+238
	DD	imagerel $LN32@UpdateDead+251
	DD	imagerel $chain$2$?UpdateDeadEntities@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateSpacialHash@World@@QEAAXXZ DD imagerel $LN39@UpdateSpac
	DD	imagerel $LN39@UpdateSpac+241
	DD	imagerel $unwind$?UpdateSpacialHash@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??_H@YAXPEAX_K1P6APEAX0@Z@Z DD imagerel $LN11@vector
	DD	imagerel $LN11@vector+45
	DD	imagerel $unwind$??_H@YAXPEAX_K1P6APEAX0@Z@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$array@VColonyController@@$04@std@@QEAA@XZ DD imagerel $LN6@array
	DD	imagerel $LN6@array+53
	DD	imagerel $unwind$??0?$array@VColonyController@@$04@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$ChunkArray@$0DOI@@@QEAA@XZ DD imagerel $LN84@ChunkArray
	DD	imagerel $LN84@ChunkArray+102
	DD	imagerel $unwind$??0?$ChunkArray@$0DOI@@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$array@VEntity@@$09@std@@QEAA@XZ DD imagerel $LN13@array
	DD	imagerel $LN13@array+69
	DD	imagerel $unwind$??0?$array@VEntity@@$09@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$SwapList@VEntity@@$09@@QEAA@XZ DD imagerel $LN15@SwapList
	DD	imagerel $LN15@SwapList+75
	DD	imagerel $unwind$??0?$SwapList@VEntity@@$09@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$array@VEntity@@$0BIGKA@@std@@QEAA@XZ DD imagerel $LN13@array
	DD	imagerel $LN13@array+69
	DD	imagerel $unwind$??0?$array@VEntity@@$0BIGKA@@std@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0?$SwapList@VEntity@@$0BIGKA@@@QEAA@XZ DD imagerel $LN15@SwapList
	DD	imagerel $LN15@SwapList+75
	DD	imagerel $unwind$??0?$SwapList@VEntity@@$0BIGKA@@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?PrintEntityInfo@World@@QEAAXMM@Z DD imagerel $LN65@PrintEntit
	DD	imagerel $LN65@PrintEntit+135
	DD	imagerel $unwind$?PrintEntityInfo@World@@QEAAXMM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$?PrintEntityInfo@World@@QEAAXMM@Z DD imagerel $LN65@PrintEntit+135
	DD	imagerel $LN65@PrintEntit+684
	DD	imagerel $chain$1$?PrintEntityInfo@World@@QEAAXMM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$?PrintEntityInfo@World@@QEAAXMM@Z DD imagerel $LN65@PrintEntit+684
	DD	imagerel $LN65@PrintEntit+704
	DD	imagerel $chain$2$?PrintEntityInfo@World@@QEAAXMM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Update@World@@QEAAXM@Z DD imagerel $LN227@Update
	DD	imagerel $LN227@Update+190
	DD	imagerel $unwind$?Update@World@@QEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$10$?Update@World@@QEAAXM@Z DD imagerel $LN227@Update+190
	DD	imagerel $LN227@Update+1253
	DD	imagerel $chain$10$?Update@World@@QEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$11$?Update@World@@QEAAXM@Z DD imagerel $LN227@Update+1253
	DD	imagerel $LN227@Update+1310
	DD	imagerel $chain$11$?Update@World@@QEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$12$?Update@World@@QEAAXM@Z DD imagerel $LN227@Update+1310
	DD	imagerel $LN227@Update+1323
	DD	imagerel $chain$12$?Update@World@@QEAAXM@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$??0World@@QEAA@XZ DD imagerel $LN380@World
	DD	imagerel $LN380@World+1949
	DD	imagerel $unwind$??0World@@QEAA@XZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateCollisions$omp$1@World@@QEAAXXZ DD imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ+69
	DD	imagerel $unwind$?UpdateCollisions$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$5$?UpdateCollisions$omp$1@World@@QEAAXXZ DD imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ+69
	DD	imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ+437
	DD	imagerel $chain$5$?UpdateCollisions$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$6$?UpdateCollisions$omp$1@World@@QEAAXXZ DD imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ+437
	DD	imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ+448
	DD	imagerel $chain$6$?UpdateCollisions$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateEntities$omp$1@World@@QEAAXXZ DD imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ+82
	DD	imagerel $unwind$?UpdateEntities$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$16$?UpdateEntities$omp$1@World@@QEAAXXZ DD imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ+82
	DD	imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ+2532
	DD	imagerel $chain$16$?UpdateEntities$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$17$?UpdateEntities$omp$1@World@@QEAAXXZ DD imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ+2532
	DD	imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ+2546
	DD	imagerel $chain$17$?UpdateEntities$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+33
	DD	imagerel $unwind$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+33
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+82
	DD	imagerel $chain$0$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$8$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+82
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+553
	DD	imagerel $chain$8$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$9$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+553
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+566
	DD	imagerel $chain$9$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$10$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+566
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+576
	DD	imagerel $chain$10$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$10$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD 021H
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+33
	DD	imagerel $unwind$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$9$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD 021H
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+33
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+82
	DD	imagerel $chain$0$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$8$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD 0104621H
	DD	047846H
	DD	056838H
	DD	0cf42fH
	DD	0de426H
	DD	0ec41aH
	DD	0f7415H
	DD	0156410H
	DD	0133408H
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+33
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+82
	DD	imagerel $chain$0$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD 020421H
	DD	0145404H
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateSpacialHash$omp$1@World@@QEAAXXZ+33
	DD	imagerel $unwind$?UpdateSpacialHash$omp$1@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateSpacialHash$omp$1@World@@QEAAXXZ DD 020c01H
	DD	0d005f20cH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$17$?UpdateEntities$omp$1@World@@QEAAXXZ DD 021H
	DD	imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ+82
	DD	imagerel $unwind$?UpdateEntities$omp$1@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$16$?UpdateEntities$omp$1@World@@QEAAXXZ DD 022ea21H
	DD	01cf4eaH
	DD	01fc4d7H
	DD	04f8c3H
	DD	05e8b5H
	DD	06d8a7H
	DD	07c899H
	DD	08b88bH
	DD	09a87aH
	DD	0a9869H
	DD	0b8858H
	DD	0c7847H
	DD	0d683eH
	DD	01de432H
	DD	01ed42aH
	DD	0256422H
	DD	0245413H
	DD	0233408H
	DD	imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateEntities$omp$1@World@@QEAAXXZ+82
	DD	imagerel $unwind$?UpdateEntities$omp$1@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateEntities$omp$1@World@@QEAAXXZ DD 030901H
	DD	0200109H
	DD	07002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$6$?UpdateCollisions$omp$1@World@@QEAAXXZ DD 021H
	DD	imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ+69
	DD	imagerel $unwind$?UpdateCollisions$omp$1@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$5$?UpdateCollisions$omp$1@World@@QEAAXXZ DD 0c2621H
	DD	08f426H
	DD	09e421H
	DD	0ad41cH
	DD	011c417H
	DD	010740fH
	DD	0f6405H
	DD	imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ
	DD	imagerel ?UpdateCollisions$omp$1@World@@QEAAXXZ+69
	DD	imagerel $unwind$?UpdateCollisions$omp$1@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateCollisions$omp$1@World@@QEAAXXZ DD 030701H
	DD	05003a207H
	DD	03002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0World@@QEAA@XZ DD imagerel ??0World@@QEAA@XZ+350
	DD	0ffffffffH
	DD	imagerel ??0World@@QEAA@XZ+531
	DD	01H
	DD	imagerel ??0World@@QEAA@XZ+663
	DD	02H
	DD	imagerel ??0World@@QEAA@XZ+714
	DD	03H
	DD	imagerel ??0World@@QEAA@XZ+1831
	DD	0ffffffffH
	DD	imagerel ??0World@@QEAA@XZ+1942
	DD	01H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$stateUnwindMap$??0World@@QEAA@XZ DD 0ffffffffH
	DD	imagerel ?dtor$0@?0???0World@@QEAA@XZ@4HA
	DD	00H
	DD	imagerel __std_terminate
	DD	00H
	DD	imagerel ?dtor$1@?0???0World@@QEAA@XZ@4HA
	DD	02H
	DD	imagerel ?dtor$2@?0???0World@@QEAA@XZ@4HA
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??0World@@QEAA@XZ DQ 00000000419930522r ; 8.69997e-314
	DD	imagerel $stateUnwindMap$??0World@@QEAA@XZ
	DQ	00000000000000000r		; 0
	DD	06H
	DD	imagerel $ip2state$??0World@@QEAA@XZ
	DQ	00000000000000060r		; 4.74303e-322
	DD	01H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0World@@QEAA@XZ DD 01f7919H
	DD	01fe868H
	DD	020d860H
	DD	021c858H
	DD	022b850H
	DD	023a848H
	DD	0249843H
	DD	025883eH
	DD	0267839H
	DD	0276834H
	DD	059742fH
	DD	058642bH
	DD	0573427H
	DD	050011aH
	DD	0e00af00cH
	DD	0c006d008H
	DD	05004H
	DD	imagerel __GSHandlerCheck_EH
	DD	imagerel $cppxdata$??0World@@QEAA@XZ
	DD	01e2H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$12$?Update@World@@QEAAXM@Z DD 0160021H
	DD	0bf800H
	DD	0ce800H
	DD	0ec800H
	DD	0fb800H
	DD	010a800H
	DD	0128800H
	DD	0146800H
	DD	02af400H
	DD	02be400H
	DD	0327400H
	DD	0313400H
	DD	imagerel $LN227@Update
	DD	imagerel $LN227@Update+190
	DD	imagerel $unwind$?Update@World@@QEAAXM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$11$?Update@World@@QEAAXM@Z DD 021H
	DD	imagerel $LN227@Update
	DD	imagerel $LN227@Update+190
	DD	imagerel $unwind$?Update@World@@QEAAXM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$10$?Update@World@@QEAAXM@Z DD 0166e21H
	DD	0bf86eH
	DD	0ce85dH
	DD	0ec84cH
	DD	0fb83bH
	DD	010a82aH
	DD	012881cH
	DD	0146816H
	DD	02af410H
	DD	02be40cH
	DD	0327408H
	DD	0313404H
	DD	imagerel $LN227@Update
	DD	imagerel $LN227@Update+190
	DD	imagerel $unwind$?Update@World@@QEAAXM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Update@World@@QEAAXM@Z DD 0b3619H
	DD	0dd824H
	DD	011981bH
	DD	0137815H
	DD	02c010fH
	DD	0c006d008H
	DD	06004H
	DD	imagerel __GSHandlerCheck
	DD	0a0H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?PrintEntityInfo@World@@QEAAXMM@Z DD 021H
	DD	imagerel $LN65@PrintEntit
	DD	imagerel $LN65@PrintEntit+135
	DD	imagerel $unwind$?PrintEntityInfo@World@@QEAAXMM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?PrintEntityInfo@World@@QEAAXMM@Z DD 040a21H
	DD	08e40aH
	DD	093405H
	DD	imagerel $LN65@PrintEntit
	DD	imagerel $LN65@PrintEntit+135
	DD	imagerel $unwind$?PrintEntityInfo@World@@QEAAXMM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?PrintEntityInfo@World@@QEAAXMM@Z DD 083f01H
	DD	02783fH
	DD	036834H
	DD	070049208H
	DD	050026003H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$SwapList@VEntity@@$0BIGKA@@@QEAA@XZ DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$array@VEntity@@$0BIGKA@@std@@QEAA@XZ DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$SwapList@VEntity@@$09@@QEAA@XZ DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$array@VEntity@@$09@std@@QEAA@XZ DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$ip2state$??0?$ChunkArray@$0DOI@@@QEAA@XZ DD imagerel ??0?$ChunkArray@$0DOI@@@QEAA@XZ+36
	DD	0ffffffffH
xdata	ENDS
;	COMDAT CONST
CONST	SEGMENT
$cppxdata$??0?$ChunkArray@$0DOI@@@QEAA@XZ DQ 00000000019930522r ; 2.11987e-315
	DQ	00000000000000000r		; 0
	DQ	00000000100000000r		; 2.122e-314
	DD	imagerel $ip2state$??0?$ChunkArray@$0DOI@@@QEAA@XZ
	DQ	00000000000000020r		; 1.58101e-322
	DD	05H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$ChunkArray@$0DOI@@@QEAA@XZ DD 020f19H
	DD	030025206H
	DD	imagerel __CxxFrameHandler3
	DD	imagerel $cppxdata$??0?$ChunkArray@$0DOI@@@QEAA@XZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$array@VColonyController@@$04@std@@QEAA@XZ DD 020601H
	DD	030025206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??_H@YAXPEAX_K1P6APEAX0@Z@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateSpacialHash@World@@QEAAXXZ DD 060f01H
	DD	07640fH
	DD	06340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?UpdateDeadEntities@World@@QEAAXXZ DD 020021H
	DD	067400H
	DD	imagerel $LN32@UpdateDead
	DD	imagerel $LN32@UpdateDead+26
	DD	imagerel $unwind$?UpdateDeadEntities@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?UpdateDeadEntities@World@@QEAAXXZ DD 021H
	DD	imagerel $LN32@UpdateDead
	DD	imagerel $LN32@UpdateDead+26
	DD	imagerel $unwind$?UpdateDeadEntities@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?UpdateDeadEntities@World@@QEAAXXZ DD 020521H
	DD	067405H
	DD	imagerel $LN32@UpdateDead
	DD	imagerel $LN32@UpdateDead+26
	DD	imagerel $unwind$?UpdateDeadEntities@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateDeadEntities@World@@QEAAXXZ DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$3$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD 021H
	DD	imagerel $LN57@UpdateColl
	DD	imagerel $LN57@UpdateColl+118
	DD	imagerel $unwind$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD 021H
	DD	imagerel $LN57@UpdateColl+118
	DD	imagerel $LN57@UpdateColl+132
	DD	imagerel $chain$0$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD 020621H
	DD	047806H
	DD	imagerel $LN57@UpdateColl+118
	DD	imagerel $LN57@UpdateColl+132
	DD	imagerel $chain$0$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD 020621H
	DD	056806H
	DD	imagerel $LN57@UpdateColl
	DD	imagerel $LN57@UpdateColl+118
	DD	imagerel $unwind$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateCollisionEntities@World@@QEAAXAEAVEntity@@0@Z DD 082f01H
	DD	02982fH
	DD	038820H
	DD	0e340aH
	DD	07006b20aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$5$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z DD 021H
	DD	imagerel $LN55@UpdateColl
	DD	imagerel $LN55@UpdateColl+82
	DD	imagerel $unwind$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$4$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z DD 0a2321H
	DD	04e423H
	DD	05741eH
	DD	066414H
	DD	07540aH
	DD	083405H
	DD	imagerel $LN55@UpdateColl
	DD	imagerel $LN55@UpdateColl+82
	DD	imagerel $unwind$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateCollisionSingleChunk@World@@QEAAXHH@Z DD 030801H
	DD	0f0048208H
	DD	0c002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$7$?UpdateCollisionChunk@World@@QEAAXHHHH@Z DD 021H
	DD	imagerel $LN89@UpdateColl
	DD	imagerel $LN89@UpdateColl+155
	DD	imagerel $unwind$?UpdateCollisionChunk@World@@QEAAXHHHH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$6$?UpdateCollisionChunk@World@@QEAAXHHHH@Z DD 0e3f21H
	DD	02983fH
	DD	038835H
	DD	047827H
	DD	056819H
	DD	0dc40fH
	DD	0e740aH
	DD	0f6405H
	DD	imagerel $LN89@UpdateColl
	DD	imagerel $LN89@UpdateColl+155
	DD	imagerel $unwind$?UpdateCollisionChunk@World@@QEAAXHHHH@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateCollisionChunk@World@@QEAAXHHHH@Z DD 061001H
	DD	0f009f210H
	DD	0d005e007H
	DD	030025003H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateCollisions@World@@QEAAXXZ DD 081401H
	DD	086414H
	DD	075414H
	DD	063414H
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$9$?UpdateColonies@World@@QEAAXXZ DD 021H
	DD	imagerel $LN116@UpdateColo
	DD	imagerel $LN116@UpdateColo+85
	DD	imagerel $unwind$?UpdateColonies@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$8$?UpdateColonies@World@@QEAAXXZ DD 0126f21H
	DD	0a686fH
	DD	05b85eH
	DD	06a850H
	DD	079842H
	DD	088834H
	DD	09782bH
	DD	016c41fH
	DD	01e7417H
	DD	01d5408H
	DD	imagerel $LN116@UpdateColo
	DD	imagerel $LN116@UpdateColo+85
	DD	imagerel $unwind$?UpdateColonies@World@@QEAAXXZ
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateColonies@World@@QEAAXXZ DD 060e01H
	DD	017010eH
	DD	0e005f007H
	DD	030026003H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?UpdateEntities@World@@QEAAXXZ DD 081401H
	DD	086414H
	DD	075414H
	DD	063414H
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@QEAA@_KAEBV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@1@@Z DD 060f01H
	DD	08640fH
	DD	07340fH
	DD	0700b320fH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?RemoveParticle@?$SwapList@VEntity@@$0BIGKA@@@QEAAXH@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??0?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@QEAA@_KAEBV?$allocator@VChunk@@@1@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Construct_n_copies_of_ty@U_Value_init_tag@std@@@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z DD 040a01H
	DD	07340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$5$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z DD 021H
	DD	imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$4$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z DD 060021H
	DD	04f400H
	DD	0d5400H
	DD	0c3400H
	DD	imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z DD 063821H
	DD	0c3438H
	DD	04f415H
	DD	0d5405H
	DD	imagerel $LN176@Emplace_re
	DD	imagerel $LN176@Emplace_re+70
	DD	imagerel $unwind$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Emplace_reallocate@AEBM@?$vector@MV?$allocator@M@std@@@std@@QEAAPEAMQEAMAEBM@Z DD 050b01H
	DD	0e007420bH
	DD	07003c005H
	DD	06002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Construct_n_copies_of_ty@U_Value_init_tag@std@@@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_KAEBU_Value_init_tag@1@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Buy_nonzero@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_K@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Ufill@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAPEAV?$vector@MV?$allocator@M@std@@@2@PEAV32@_KU_Value_init_tag@2@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Change_array@?$vector@MV?$allocator@M@std@@@std@@AEAAXQEAM_K1@Z DD 081401H
	DD	096414H
	DD	085414H
	DD	073414H
	DD	070103214H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Umove@?$vector@MV?$allocator@M@std@@@std@@AEAAPEAMPEAM00@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Buy_nonzero@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_K@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Xlength@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@CAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Buy_raw@?$vector@V?$vector@MV?$allocator@M@std@@@std@@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@2@@std@@AEAAX_K@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Xlength@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@CAXXZ DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?_Buy_raw@?$vector@VChunk@@V?$allocator@VChunk@@@std@@@std@@AEAAX_K@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?allocate@?$allocator@VChunk@@@std@@QEAAPEAVChunk@@_K@Z DD 010401H
	DD	04204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Uninitialized_value_construct_n@V?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@std@@@std@@YAPEAV?$vector@MV?$allocator@M@std@@@0@PEAV10@_KAEAV?$allocator@V?$vector@MV?$allocator@M@std@@@std@@@0@@Z DD 020601H
	DD	030023206H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Uninitialized_move@PEAMV?$allocator@M@std@@@std@@YAPEAMQEAM0PEAMAEAV?$allocator@M@0@@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Uninitialized_value_construct_n@V?$allocator@VChunk@@@std@@@std@@YAPEAVChunk@@PEAV1@_KAEAV?$allocator@VChunk@@@0@@Z DD 0a1a01H
	DD	09741aH
	DD	08641aH
	DD	07541aH
	DD	06341aH
	DD	0e016321aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Copy_memmove@PEAMPEAM@std@@YAPEAMPEAM00@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$_Emplace_back@$$V@?$_Uninitialized_backout_al@V?$allocator@VChunk@@@std@@@std@@QEAAXXZ DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$??$construct@VChunk@@$$V@?$_Default_allocator_traits@V?$allocator@VChunk@@@std@@@std@@SAXAEAV?$allocator@VChunk@@@1@QEAVChunk@@@Z DD 020601H
	DD	030023206H
END
